// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $('iframe').attr('src', 'http://www3.nhk.or.jp/news/html/20140201/k10014948321000.html');
  });

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
